#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

language: python

python:
  - "3.6"

before_install:
  - cp secrets-dummy.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - HA_VERSION=$(<.HA_VERSION)

install:
  - pip3 install homeassistant==${HA_VERSION}
  - pip3 install boltons
  - pip3 install future
  - pip3 install https://github.com/renemarc/py-lightpack/archive/feature/expand-api-command-set.tar.gz

script:
  - hass --script check_config --config . --files
